### ISSUE TITLE
Viewer not remapping class names

### ISSUE THREAD

**Issue by Elioby** [lucko/spark-viewer#38] opened 2022-06-09 11:54 UTC
Remapping method names is working fine, however class names don't seem to be remapped. For example, `net.minecraft.server.level.WorldServer.tick` is the correctly remapped method from `net.minecraft.server.level.WorldServer.a`, but the class name is not remapped from `WorldServer` to `ServerLevel`.

**Comment by lucko** [comment] 2022-06-09 20:42
Duplicate of #27

**Closed by lucko** 2022-06-09 20:42 UTC
